In [49]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import  date

In [50]:
df = pd.read_csv("../data/data.csv")
df.columns = [col.replace(" ","_").strip().lower() for col in df.columns]
df.head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

# Categorical Features

In [51]:
cat_col = df.select_dtypes("object")
cat_col_name = cat_col.columns.to_list()
cat_col.head()

,make,model,engine_fuel_type,transmission_type,driven_wheels,market_category,vehicle_size,vehicle_style
0,BMW,1 Series M,premium unleaded (required),MANUAL,rear wheel drive,"Factory Tuner,Luxury,High-Performance",Compact,Coupe
1,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Convertible
2,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,High-Performance",Compact,Coupe
3,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Coupe
4,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,Luxury,Compact,Convertible

In [52]:
for col in cat_col.columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [53]:
df[cat_col_name]

,make,model,engine_fuel_type,transmission_type,driven_wheels,market_category,vehicle_size,vehicle_style
0,BMW,1 Series M,premium unleaded (required),MANUAL,rear wheel drive,"Factory Tuner,Luxury,High-Performance",Compact,Coupe
1,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Convertible
2,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,High-Performance",Compact,Coupe
3,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Coupe
4,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,Luxury,Compact,Convertible
...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11910,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11911,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11912,Acura,ZDX,premium unleaded (recommended),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11913,Lincoln,Zephyr,regular unleaded,AUTOMATIC,front wheel drive,Luxury,Midsize,Sedan

make,
model,
market_category,
vehicle_style

In [54]:
top_9_make = df["make"].value_counts().nlargest(9).index
df["make"] = df["make"].apply(lambda x: x if x in top_9_make else "other") 
top_9_model = df["model"].value_counts().nlargest(9)
df["model"] = df["model"].apply(lambda x: x if x in top_9_model else "other") 

catagery = list(set(",".join(df["market_category"]. unique().tolist()).split(",")))
for cat in catagery:
    df[cat] = df["market_category"].apply(lambda x:  1 if cat in x else 0)
df.columns  =  [col.replace(" ","_").strip().lower() for col in df.columns]
df.drop(columns="market_category",inplace=True)

top_9_style = df["vehicle_style"].value_counts().nlargest(9).index
df["vehicle_style"] =  df["vehicle_style"].apply(lambda x: x if x in top_9_style else "other")

In [55]:
df.select_dtypes("object")

,make,model,engine_fuel_type,transmission_type,driven_wheels,vehicle_size,vehicle_style
0,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Coupe
1,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Convertible
2,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Coupe
3,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Coupe
4,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Convertible
...,...,...,...,...,...,...,...
11909,other,other,premium unleaded (required),AUTOMATIC,all wheel drive,Midsize,4dr Hatchback
11910,other,other,premium unleaded (required),AUTOMATIC,all wheel drive,Midsize,4dr Hatchback
11911,other,other,premium unleaded (required),AUTOMATIC,all wheel drive,Midsize,4dr Hatchback
11912,other,other,premium unleaded (recommended),AUTOMATIC,all wheel drive,Midsize,4dr Hatchback
11913,other,other,regular unleaded,AUTOMATIC,front wheel drive,Midsize,Sedan

# numerical columns

In [56]:
num_col = df.select_dtypes(exclude="object").columns.to_list()

In [57]:


for col in num_col:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [58]:
df[num_col].head()

,year,engine_hp,engine_cylinders,number_of_doors,highway_mpg,city_mpg,popularity,msrp,high-performance,diesel,crossover,hybrid,hatchback,flex_fuel,performance,factory_tuner,luxury,exotic
0,2011,335.0,6.0,2.0,26,19,3916,46135,1,0,0,0,0,0,1,1,1,0
1,2011,300.0,6.0,2.0,28,19,3916,40650,0,0,0,0,0,0,1,0,1,0
2,2011,300.0,6.0,2.0,28,20,3916,36350,1,0,0,0,0,0,1,0,1,0
3,2011,230.0,6.0,2.0,28,18,3916,29450,0,0,0,0,0,0,1,0,1,0
4,2011,230.0,6.0,2.0,28,18,3916,34500,0,0,0,0,0,0,0,0,1,0

In [59]:
df.select_dtypes("object").head()

,make,model,engine_fuel_type,transmission_type,driven_wheels,vehicle_size,vehicle_style
0,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Coupe
1,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Convertible
2,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Coupe
3,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Coupe
4,other,other,premium unleaded (required),MANUAL,rear wheel drive,Compact,Convertible

In [60]:
df.to_csv("../data/processed.csv",index=False)